In [18]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
Y = np.arange(8).reshape(4,2)
poly = PolynomialFeatures(degree = 2)
poly.fit_transform(Y)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.]])

In [ ]:
# Row 1: [1., 0., 1., 0., 0., 1.]

#     This corresponds to the original data [0, 1]. Here's what each element represents:
#         1.: Bias term (constant term).
#         0.: First variable (X1).
#         1.: Second variable (X2).
#         0.: Product of the first and second variables (X1 * X2).
#         0.: Square of the first variable (X1^2).
#         1.: Square of the second variable (X2^2).

# Row 2: [1., 2., 3., 6., 4., 9.]

#     This corresponds to the original data [2, 3]. Here's what each element represents:
#         1.: Bias term.
#         2.: First variable (X1).
#         3.: Second variable (X2).
#         6.: Product of the first and second variables (X1 * X2).
#         4.: Square of the first variable (X1^2).
#         9.: Square of the second variable (X2^2).

# Row 3: [1., 4., 5., 20., 16., 25.]

#     This corresponds to the original data [4, 5]. Here's what each element represents:
#         1.: Bias term.
#         4.: First variable (X1).
#         5.: Second variable (X2).
#         20.: Product of the first and second variables (X1 * X2).
#         16.: Square of the first variable (X1^2).
#         25.: Square of the second variable (X2^2).

# Row 4: [1., 6., 7., 42., 36., 49.]

#     This corresponds to the original data [6, 7]. Here's what each element represents:
#         1.: Bias term.
#         6.: First variable (X1).
#         7.: Second variable (X2).
#         42.: Product of the first and second variables (X1 * X2).
#         36.: Square of the first variable (X1^2).
#         49.: Square of the second variable (X2^2).


In [17]:
# pipeline
#First, import the necessary packages.
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np


#Next, create an object of Pipeline tool
Stream_model = Pipeline([('poly', PolynomialFeatures(degree = 3)),('linear', LinearRegression(fit_intercept = False))])

#Provide the size of array and order of polynomial data to fit the model.
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
Stream_model.fit(x[:, np.newaxis], y)

#Calculate the input polynomial coefficients.
Stream_model.named_steps['linear'].coef_, Stream_model.predict(x[:, np.newaxis])

[0 1 2 3 4]


(array([ 3., -2.,  1., -1.]), array([  3.,   1.,  -5., -21., -53.]))