In [5]:
# SVR
from sklearn import svm
X = [[1, 1], [2, 2]]
y = [1, 2]
SVRReg = svm.SVR(kernel = 'linear', gamma = 'auto')
SVRReg.fit(X, y).get_params(deep = True)

{'C': 1.0,
 'cache_size': 200,
 'coef0': 0.0,
 'degree': 3,
 'epsilon': 0.1,
 'gamma': 'auto',
 'kernel': 'linear',
 'max_iter': -1,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [6]:
SVRReg.coef_

array([[0.4, 0.4]])

In [7]:
SVRReg.predict([[1,1]])

array([1.1])

In [13]:
# NuSVR
from sklearn.svm import NuSVR
import numpy as np
n_samples, n_features = 20, 15
np.random.seed(0)
y = np.random.randn(n_samples)
X = np.random.randn(n_samples, n_features)
NuSVRReg = NuSVR(kernel = 'linear', gamma = 'auto', C = 1.0, nu = 0.1)
NuSVRReg.fit(X, y).get_params(deep = True)

{'C': 1.0,
 'cache_size': 200,
 'coef0': 0.0,
 'degree': 3,
 'gamma': 'auto',
 'kernel': 'linear',
 'max_iter': -1,
 'nu': 0.1,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [14]:
NuSVRReg.coef_

array([[-0.14904483,  0.04596145,  0.22605216, -0.08125403,  0.06564533,
         0.01104285,  0.04068767,  0.2918337 , -0.13473211,  0.36006765,
        -0.2185713 , -0.31836476, -0.03048429,  0.16102126, -0.29317051]])

In [15]:
# LinearSVR
from sklearn.svm import LinearSVR
from sklearn.datasets import make_regression
X, y = make_regression(n_features = 4, random_state = 0)
LSVRReg = LinearSVR(dual = False, random_state = 0,
                    loss = 'squared_epsilon_insensetive', tol = 1e-5)
LSVRReg.fit(X, y).get_params(deep = True)

InvalidParameterError: The 'loss' parameter of LinearSVR must be a str among {'squared_epsilon_insensitive', 'epsilon_insensitive'}. Got 'squared_epsilon_insensetive' instead.