In [2]:
# SVC
import numpy as np
from sklearn.svm import SVC
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
SVCClf = SVC(kernel = 'linear', gamma = 'scale', shrinking = False,)
SVCClf.fit(X, y).get_params(deep = True)

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': False,
 'tol': 0.001,
 'verbose': False}

In [3]:
SVCClf.coef_

array([[0.5, 0.5]])

In [4]:
SVCClf.predict([[-0.5,-0.8]])

array([1])

In [5]:
SVCClf.n_support_

array([1, 1])

In [6]:
SVCClf.support_vectors_

array([[-1., -1.],
       [ 1.,  1.]])

In [7]:
SVCClf.support_

array([0, 2])

In [8]:
SVCClf.intercept_

array([-0.])

In [9]:
SVCClf.fit_status_

0

In [14]:
# NuSVC
import numpy as np
from sklearn.svm import NuSVC
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
NuSVCClf = NuSVC(kernel = 'linear',gamma = 'scale', shrinking = False, nu = 0.7)
NuSVCClf.fit(X, y).get_params(deep = True)

{'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'nu': 0.7,
 'probability': False,
 'random_state': None,
 'shrinking': False,
 'tol': 0.001,
 'verbose': False}

In [16]:
# LinearSVC
from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification
X, y = make_classification(n_features = 4, random_state = 0)
LSVCClf = LinearSVC(dual = False, random_state = 0, penalty = 'l1',tol = 1e-5)
LSVCClf.fit(X, y).get_params(deep = True)

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'loss': 'squared_hinge',
 'max_iter': 1000,
 'multi_class': 'ovr',
 'penalty': 'l1',
 'random_state': 0,
 'tol': 1e-05,
 'verbose': 0}

In [17]:
LSVCClf.predict([[0,0,0,0]])

array([1])

In [18]:
LSVCClf.coef_

array([[0.        , 0.        , 0.91214599, 0.22630641]])

In [19]:
LSVCClf.intercept_

array([0.26860191])